name: prefauction
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - cudatoolkit=10.1.243
  - cycler=0.10.0=py37_0
  - freetype=2.10.4
  - icu=64.2
  - intel-openmp=2020.0=166
  - joblib=1.0.0
  - jpeg=9c
  - kiwisolver=1.3.1
  - libblas=3.8.0=15_mkl
  - libcblas=3.8.0=15_mkl
  - libclang=9.0.1
  - liblapack=3.8.0=15_mkl
  - liblapacke=3.8.0=15_mkl
  - libopencv=4.2.0=py37_6
  - libpng=1.6.37
  - libtiff=4.1.0
  - libuv=1.40.0
  - libwebp=1.0.2
  - lz4-c=1.9.3
  - matplotlib=3.2.1=0
  - matplotlib-base=3.2.1
  - mkl=2020.0=166
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.0
  - ninja=1.10.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46=py37_0
  - opencv=4.2.0=py37_6
  - openssl=1.1.1i
  - pandas=1.0.3
  - pillow=8.1.0
  - pip=20.3.3
  - py-opencv=4.2.0
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - python=3.7.7
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytorch=1.7.0
  - pytz=2021.1
  - qt=5.12.5
  - scipy=1.6.0
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - torchaudio=0.7.0=py37
  - torchvision=0.8.1=py37_cu101
  - tornado=6.1
  - tqdm=4.46.0=py_0
  - typing_extensions=3.7.4.3
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - argon2-cffi==20.1.0
    - ase==3.21.1
    - async-generator==1.10
    - attrs==20.3.0
    - backcall==0.2.0
    - bleach==3.2.1
    - cached-property==1.5.2
    - cffi==1.14.4
    - chardet==4.0.0
    - click==7.1.2
    - colorama==0.4.4
    - configparser==5.0.1
    - decorator==4.4.2
    - defusedxml==0.6.0
    - docker-pycreds==0.4.0
    - entrypoints==0.3
    - exifread==2.3.2
    - future==0.18.2
    - gitdb==4.0.5
    - gitpython==3.1.11
    - googledrivedownloader==0.4
    - h5py==3.1.0
    - idna==2.10
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.3
    - importlib-metadata==3.3.0
    - ipykernel==5.4.2
    - ipython==7.19.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - isodate==0.6.0
    - jedi==0.17.2
    - jinja2==2.11.2
    - json5==0.9.5
    - jsonschema==3.2.0
    - jupyter-client==6.1.7
    - jupyter-core==4.7.0
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==1.2.0
    - jupyterlab-widgets==1.0.0
    - llvmlite==0.35.0
    - markupsafe==1.1.1
    - mistune==0.8.4
    - moviepy==1.0.3
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.0.8
    - nest-asyncio==1.4.3
    - networkx==2.5
    - notebook==6.1.5
    - numba==0.52.0
    - onnx==1.7.0
    - onnxruntime-gpu==1.3.0
    - open3d==0.12.0
    - packaging==20.8
    - pandocfilters==1.4.3
    - parso==0.7.1
    - pickleshare==0.7.5
    - proglog==0.1.9
    - prometheus-client==0.9.0
    - promise==2.3
    - prompt-toolkit==3.0.8
    - protobuf==3.12.2
    - psutil==5.8.0
    - pycparser==2.20
    - pygments==2.7.3
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - pyrsistent==0.17.3
    - python-louvain==0.15
    - pyyaml==5.3.1
    - pyzmq==20.0.0
    - rdflib==5.0.0
    - requests==2.25.1
    - scikit-learn==0.24.1
    - seaborn==0.10.1
    - send2trash==1.5.0
    - sentry-sdk==0.19.5
    - shortuuid==1.0.1
    - sklearn==0.0
    - smmap==3.0.4
    - subprocess32==3.5.4
    - terminado==0.9.1
    - testpath==0.4.4
    - threadpoolctl==2.1.0
    - torch-cluster==1.5.8
    - torch-geometric==1.6.3
    - torch-scatter==2.0.5
    - torch-sparse==0.6.8
    - torch-spline-conv==1.2.0
    - traitlets==5.0.5
    - transforms3d==0.3.1
    - typing-extensions==3.7.4.2
    - urllib3==1.26.2
    - wandb==0.10.12
    - watchdog==1.0.2
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - zipp==3.4.0
